// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        google()
        maven {url 'https://maven.google.com'}
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath "io.realm:realm-gradle-plugin:10.15.1"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.1'

        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.0'
    }
}

allprojects {
    version = VERSION_NAME
    group = GROUP

    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
        }
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
        maven {
            url 'https://jitpack.io'
        }
        flatDir {
            dirs 'libs'
        }
    }
}


task clean(type: Delete) {
    delete rootProject.buildDir
}
