#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Wed Jan 24 19:22:47 IST 2018
apiSecret=b643ca8d04859f05c88a8900b1ee416c6960e18f17dae6ccf21ad340de7e41f1
