//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-10/27/2009 06:09 PM(mockbuild)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 06:27:19 PM PST 
//


package com.dalread.util.sardine.model;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Namespace;
import org.simpleframework.xml.Root;

/**
 * <p>Java class for anonymous complex type.</p>
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{DAV:}lockscope"/&gt;
 *         &lt;element ref="{DAV:}locktype"/&gt;
 *         &lt;element ref="{DAV:}depth"/&gt;
 *         &lt;element ref="{DAV:}owner" minOccurs="0"/&gt;
 *         &lt;element ref="{DAV:}timeout" minOccurs="0"/&gt;
 *         &lt;element ref="{DAV:}locktoken" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@Root(strict = false)
@Namespace(prefix = "D", reference = "DAV:")
public class Activelock {

    @Element
    private com.dalread.util.sardine.model.Lockscope lockscope;

    @Element
    private com.dalread.util.sardine.model.Locktype locktype;

    @Element
    private String depth;

    @Element(required = false)
    private com.dalread.util.sardine.model.Owner owner;

    @Element(required = false)
    private String timeout;

    @Element(required = false)
    private com.dalread.util.sardine.model.Locktoken locktoken;

    /**
     * Gets the value of the lockscope property.
     * 
     * @return
     *     possible object is
     *     {@link com.dalread.util.sardine.model.Lockscope }
     *     
     */
    public com.dalread.util.sardine.model.Lockscope getLockscope() {
        return lockscope;
    }

    /**
     * Sets the value of the lockscope property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.dalread.util.sardine.model.Lockscope }
     *     
     */
    public void setLockscope(Lockscope value) {
        this.lockscope = value;
    }

    /**
     * Gets the value of the locktype property.
     * 
     * @return
     *     possible object is
     *     {@link com.dalread.util.sardine.model.Locktype }
     *     
     */
    public com.dalread.util.sardine.model.Locktype getLocktype() {
        return locktype;
    }

    /**
     * Sets the value of the locktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.dalread.util.sardine.model.Locktype }
     *     
     */
    public void setLocktype(Locktype value) {
        this.locktype = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepth(String value) {
        this.depth = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link com.dalread.util.sardine.model.Owner }
     *     
     */
    public com.dalread.util.sardine.model.Owner getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.dalread.util.sardine.model.Owner }
     *     
     */
    public void setOwner(Owner value) {
        this.owner = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeout(String value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the locktoken property.
     * 
     * @return
     *     possible object is
     *     {@link com.dalread.util.sardine.model.Locktoken }
     *     
     */
    public com.dalread.util.sardine.model.Locktoken getLocktoken() {
        return locktoken;
    }

    /**
     * Sets the value of the locktoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.dalread.util.sardine.model.Locktoken }
     *     
     */
    public void setLocktoken(Locktoken value) {
        this.locktoken = value;
    }

}
